name: infoctess_koneqt
description: Infoctess UEW informative and social platform.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+2

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  firebase_remote_config:
  flutter_quill: 7.1.11
  cached_network_image: ^3.2.3
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  # video_player: ^2.4.10
  url_launcher: ^6.1.7
  # go_router: ^6.0.0
  animations: ^2.0.7
  detectable_text_field: ^2.0.4
  flutter_native_splash: ^2.2.16
  sqflite: ^2.2.5
  path:
  # syncfusion_flutter_pdfviewer: ^20.1.50-beta
  path_provider: ^2.0.11
  intl:
  flutter_slidable: ^3.0.0
  flutter_local_notifications: ^13.0.0
  timezone:
  image_gallery_saver: ^1.7.1
  status_alert: ^1.0.1
  flutter_native_timezone:
  resize: ^1.0.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_expandable_fab: ^1.7.1
  tuple: ^2.0.1
  calendar_timeline: ^1.1.2
  mime: ^1.0.4
  file_picker:
  # flutter_download_manager:
  connectivity_plus: ^4.0.1
  # open_file: ^3.3.2
  http:
  package_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/infoctess_logo_bg.png

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - .env

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
