// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgX-T2RgNeXUebc1lPh4atJAqyA2h2gWo',
    appId: '1:900049755309:web:c37538cedf4843df34fa24',
    messagingSenderId: '900049755309',
    projectId: 'infoctess-koneqt',
    authDomain: 'infoctess-koneqt.firebaseapp.com',
    storageBucket: 'infoctess-koneqt.appspot.com',
    measurementId: 'G-CH9P5V55D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn_vFFaVI0oE11Gf_CVSJlp5841TsKeEY',
    appId: '1:900049755309:android:33634445e19b3aff34fa24',
    messagingSenderId: '900049755309',
    projectId: 'infoctess-koneqt',
    storageBucket: 'infoctess-koneqt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEqryuyiedPfWOGmxJMr9jzohVxQff-lM',
    appId: '1:900049755309:ios:62425598fdbf141534fa24',
    messagingSenderId: '900049755309',
    projectId: 'infoctess-koneqt',
    storageBucket: 'infoctess-koneqt.appspot.com',
    iosClientId: '900049755309-rep3v01m12kd4nbp27cuulq346neqdv8.apps.googleusercontent.com',
    iosBundleId: 'com.arksoft.infoctessKoneqt',
  );
}
